general {
    after_sleep_cmd = niri msg action power-off-monitors # turn of screen after sleep (not strictly necessary, but just in case)
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    before_sleep_cmd = qs -c noctalia-shell ipc call lockScreen lock
    after_sleep_cmd = niri msg action power-on-monitors
}


listener {
    timeout = 1200
    on-timeout = niri msg action power-off-monitors       # screen off

}

listener {
    timeout = 2000
    on-timeout = systemctl suspend 
}
