color0 #0b141a
color1 #ffb4ab
color2 #52dbcb
color3 #82d5c9
color4 #91cef4
color5 #52dbcb
color6 #82d5c9
color7 #dae4ec
color8 #8093a1
color9 #ffb4ab
color10 #52dbcb
color11 #82d5c9
color12 #91cef4
color13 #52dbcb
color14 #82d5c9
color15 #dae4ec

cursor                #dae4ec
cursor_text_color     #0b141a
background            #0b141a
foreground            #dae4ec
selection_foreground  #b6c9d8
selection_background  #374955
active_border_color   #52dbcb
inactive_border_color #374955
url_color             #52dbcb

active_tab_foreground   #003732
active_tab_background   #52dbcb
inactive_tab_foreground #b6c9d8
inactive_tab_background #374955
cursor_trail_color      #b6c9d8
background_opacity 0.8
