# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(251A19)
$foreground = rgb(F8D6D6)
$color0 = rgb(4E403F)
$color1 = rgb(3A0B0B)
$color2 = rgb(790D0C)
$color3 = rgb(723636)
$color4 = rgb(A21112)
$color5 = rgb(A15C5B)
$color6 = rgb(B16867)
$color7 = rgb(EDBDBC)
$color8 = rgb(A68483)
$color9 = rgb(4E0E0F)
$color10 = rgb(A11110)
$color11 = rgb(984848)
$color12 = rgb(D81718)
$color13 = rgb(D77A79)
$color14 = rgb(EC8B89)
$color15 = rgb(EDBDBC)
